services:
  stream:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]